spring.application.name=Board Game Collection API

spring.datasource.url=jdbc:mysql://localhost:3306/boardgames
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update