INSERT INTO users (full_name, email, password, role)
VALUES ('Administrator', 'admin@example.com', '$2a$12$WuQP5i01mdP0FrKMzMD8FeW7gnAx0fGfRwG0Z04AXNvhXXm8mqmcq', 'ADMIN');


INSERT INTO categories (name)
VALUES ('Abstract Strategy'),
       ('Adventure'),
       ('Card Game'),
       ('Children''s Game'),
       ('City Building'),
       ('Civilization'),
       ('Deduction'),
       ('Dice'),
       ('Economic'),
       ('Educational'),
       ('Fantasy'),
       ('Fighting'),
       ('Horror'),
       ('Humor'),
       ('Medieval'),
       ('Miniatures'),
       ('Movies / TV / Radio theme'),
       ('Murder / Mystery'),
       ('Music'),
       ('Mythology'),
       ('Party Game'),
       ('Pirates'),
       ('Political'),
       ('Puzzle'),
       ('Racing'),
       ('Science Fiction'),
       ('Sports'),
       ('Trains'),
       ('World War II'),
       ('Zombies');

INSERT INTO games (title, description, min_players, max_players, play_time, publisher, release_year)
VALUES ('Catan', 'Klasyczna gra osadnicza polegająca na zbieraniu surowców i budowie osad', 3, 4, 60, 'KOSMOS', 1995),
       ('Ticket to Ride', 'Gra o budowaniu tras kolejowych przez Amerykę Północną', 2, 5, 45, 'Days of Wonder', 2004),
       ('Carcassonne', 'Gra układania płytek i zajmowania terenów w średniowiecznej Francji', 2, 5, 35, 'Hans im Glück',
        2000),
       ('Terraforming Mars', 'Gra strategiczna o terraformowaniu Czerwonej Planety', 1, 5, 120, 'FryxGames', 2016),
       ('7 Wonders', 'Gra karciana o rozwoju starożytnych cywilizacji', 2, 7, 30, 'Repos Production', 2010),
       ('Azul', 'Abstrakcyjna gra o układaniu płytek w stylu portugalskich azulejos', 2, 4, 30, 'Next Move Games',
        2017),
       ('Dixit', 'Kreatywna gra skojarzeń z pięknymi ilustracjami', 3, 6, 30, 'Libellud', 2008),
       ('Pandemic', 'Kooperacyjna gra o powstrzymywaniu globalnej pandemii', 2, 4, 45, 'Z-Man Games', 2008),
       ('Codenames', 'Gra drużynowa o odgadywaniu haseł na podstawie podpowiedzi', 2, 8, 15, 'Czech Games Edition',
        2015),
       ('Splendor', 'Gra ekonomiczna o handlu klejnotami w renesansie', 2, 4, 30, 'Space Cowboys', 2014),
       ('Terra Mystica', 'Głęboka gra strategiczna o rasach fantasy walczących o terytorium', 2, 5, 100,
        'Feuerland Spiele', 2012),
       ('Gloomhaven', 'Kampanijna gra fantasy z rozwiniętą mechaniką walki', 1, 4, 120, 'Cephalofair Games', 2017),
       ('Wingspan', 'Gra o obserwacji ptaków z pięknymi komponentami', 1, 5, 50, 'Stonemaier Games', 2019),
       ('Blood Rage', 'Gra o wikińskich klanach w czasach Ragnaroku', 2, 4, 60, 'CMON', 2015),
       ('The Castles of Burgundy', 'Klasyczna gra o rozwoju posiadłości w średniowiecznej Francji', 2, 4, 60,
        'Ravensburger', 2011),
       ('Everdell', 'Przyjemna gra o budowie leśnego miasta przez zwierzęta', 1, 4, 50, 'Starling Games', 2018),
       ('Scythe', 'Gra alternatywnej historii w stylu dieselpunku', 1, 5, 115, 'Stonemaier Games', 2016),
       ('Brass: Birmingham', 'Gra ekonomiczna o rewolucji przemysłowej w Anglii', 2, 4, 120, 'Roxley', 2018),
       ('Arkham Horror: The Card Game', 'Kooperacyjna gra karciana z nurtu horroru lovecraftowskiego', 1, 2, 60,
        'Fantasy Flight Games', 2016),
       ('Spirit Island', 'Kooperacyjna gra, w której gracze są duchami broniącymi wyspy', 1, 4, 90,
        'Greater Than Games', 2017);


INSERT INTO games_categories (game_id, category_id)
VALUES
    (1, 9),
    (1, 21),
    (2, 28),
    (2, 26),
    (3, 5),
    (3, 15),
    (4, 6),
    (4, 9),
    (4, 26),
    (5, 3),
    (5, 6),
    (5, 1),
    (6, 1),
    (6, 24),
    (7, 21),
    (7, 14),
    (8, 10),
    (9, 21),
    (9, 7),
    (10, 9),
    (10, 15),
    (11, 1),
    (11, 11),
    (11, 5),
    (12, 11),
    (12, 16),
    (12, 2),
    (13, 3),
    (13, 4),
    (13, 10),
    (14, 11),
    (14, 12),
    (14, 16),
    (15, 9),
    (15, 15),
    (15, 8),
    (16, 3),
    (16, 11),
    (16, 4),
    (17, 9),
    (17, 5),
    (17, 26),
    (18, 9),
    (18, 23),
    (19, 3),
    (19, 13),
    (19, 2),
    (20, 11),
    (20, 10);